export enum AvailabilityForChange {
  CITY_OR_STATE = 'CITY_OR_STATE',
  CITY_ONLY = 'CITY_ONLY',
  NO = 'NO',
}

export enum HumanRace {
  BLACK = 'BLACK',
  BROWN = 'BROWN',
  WHITE = 'WHITE',
  ASIATIC = 'ASIATIC',
  INDIGENOUS = 'INDIGENOUS',
  RATHER_NOT_SAY = 'RATHER_NOT_SAY',
}

export enum SexualOrientation {
  HOMOSEXUAL = 'HOMOSEXUAL',
  HETEROSEXUAL = 'HETEROSEXUAL',
  BISEXUAL = 'BISEXUAL',
  PANSEXUAL = 'PANSEXUAL',
  RATHER_NOT_SAY = 'RATHER_NOT_SAY',
}

export enum Pcd {
  NOT_PCD = 'NOT_PCD',
  PHYSICAL_IMPAIRED = 'PHYSICAL_IMPAIRED',
  HEARING_IMPAIRED = 'HEARING_IMPAIRED',
  VISUALLY_IMPAIRED = 'VISUALLY_IMPAIRED',
  MENTALLY_IMPAIRED = 'MENTALLY_IMPAIRED',
  MOTOR_DISABILITY = 'MOTOR_DISABILITY',
  RATHER_NOT_SAY = 'RATHER_NOT_SAY',
}

export enum LivingPlace {
  CITY_CENTER_NEIGHBORHOOD = 'CITY_CENTER_NEIGHBORHOOD',
  FORMAL_NEIGHBORHOOD = 'FORMAL_NEIGHBORHOOD',
  COMMUNITY_PERIPHERY = 'COMMUNITY_PERIPHERY',
  COUNTRY_SIDE = 'COUNTRY_SIDE',
  RATHER_NOT_SAY = 'RATHER_NOT_SAY',
}

export enum WhereStudiedHighSchool {
  PUBLIC = 'PUBLIC',
  PRIVATE = 'PRIVATE',
  RATHER_NOT_SAY = 'RATHER_NOT_SAY',
}

export enum FamilyIncome {
  LESS_THAN_ONE = 'LESS_THAN_ONE',
  BETWEEN_ONE_TWO = 'BETWEEN_ONE_TWO',
  BETWEEN_THREE_FIVE = 'BETWEEN_THREE_FIVE',
  MORE_THAN_FIVE = 'MORE_THAN_FIVE',
  RATHER_NOT_SAY = 'RATHER_NOT_SAY',
}

export enum Studentship {
  GOVERNMENT_SHIP = 'GOVERNMENT_SHIP',
  UNIVERSITY_SHIP = 'UNIVERSITY_SHIP',
  EMPLOYER_SHIP = 'EMPLOYER_SHIP',
  NO = 'NO',
}

export enum InternshipModel {
  OFFICE = 'OFFICE',
  FROM_HOME = 'FROM_HOME',
  HYBRID = 'HYBRID',
}

export enum Gender {
  MALE = 'MALE',
  FEMALE = 'FEMALE',
  TRANSGENDER = 'TRANSGENDER',
  GENDERNEUTRAL = 'GENDERNEUTRAL',
  NONBINARY = 'NONBINARY',
  OTHERS = 'OTHERS',
  NOTINFORM = 'NOTINFORM',
}
