export enum ErrorCodes {
  GENERIC = 'GENERIC',
  VALIDATION = 'VALIDATION',
  INVALID_TOKEN = 'INVALID_TOKEN',
  USER_NOT_REGISTERED = 'USER_NOT_REGISTERED',
  USER_REGISTERED_FROM_THIRD_OAUTH = 'USER_REGISTERED_FROM_THIRD_OAUTH',
  EXPIRED_TOKEN = 'EXPIRED_TOKEN',
  EXPIRED_REFRESH_TOKEN = 'EXPIRED_REFRESH_TOKEN',
  EMPLOYEE_ALREADY_REGISTERED = 'EMPLOYEE_ALREADY_REGISTERED',
  EMPLOYER_ALREADY_REGISTERED = 'EMPLOYER_ALREADY_REGISTERED',
  USER_ALREADY_REGISTERED = 'USER_ALREADY_REGISTERED',
  EMAIL_NOT_CONFIRMED = 'EMAIL_NOT_CONFIRMED',
  EMAIL_ALREADY_CONFIRMED = 'EMAIL_ALREADY_CONFIRMED',
  EMAIL_OR_PASSWORD_INVALID = 'EMAIL_OR_PASSWORD_INVALID',
  DATA_ALREADY_EXISTS = 'DATA_ALREADY_EXISTS',
  PROFILE_NOT_COMPLETED = 'PROFILE_NOT_COMPLETED',
  CONFIRMATION_EMAIL_ALREADY_SENT = 'CONFIRMATION_EMAIL_ALREADY_SENT',

  // HTTP ERRORS
  UNAUTHORIZED = 'UNAUTHORIZED',
  NOT_FOUND = 'NOT_FOUND',
  FORBIDDEN = 'FORBIDDEN',
  INTERNAL_SERVER_ERROR = 'INTERNAL_SERVER_ERROR',
  BAD_REQUEST = 'BAD_REQUEST',

  // DATABASE ERRORS
  MONGO_DB = 'MONGO_DB',
}
